//#include "opencv2/opencv.hpp"
extern void show1();//이 파일 바깥에 있어.
extern void show2();
extern void show3();
extern void show4();
extern void show5();
extern void show6();
extern void show7();
extern void show8();
extern void show9();
extern void show10();
extern void show11();
extern void show12();
extern void show13();
extern void show14();
extern void show15();
extern void show16();
extern void show17();
extern void show18();
extern void show19();
extern void show20();
extern void show21();
extern void show22();
extern void show23();
extern void show24();
extern void show25();
extern void show26();
extern void show27();
extern void show28();
extern void show29();
extern void show30();
extern void show31();
extern void show32();
extern void show33();
extern void show34();
extern void show35();
extern void show36();
extern void show37();
extern void show38();
extern void show39();
extern void show40();
extern void show41();
extern void show42();
extern void show43();
extern void show44();
extern void show45();
extern void show46();
extern void show47();

extern void yaku1();
#include <iostream>

int main()
{
    std::cout << "OpneCV!\n";
    //show1();
    //show2();
    //show3();
    //show4();
    //show5();
    //show6();
    //show7();
    //show8();
    //show9();
    //show10();
    //show11();
    //show12();
    //show13();
    //show14();
    //show15();
    //show16();
    //show17();
    //show18();
    //show19();
    //show20();
    //show21();
    //show22();
    //show23();
    //show24();
    //show25();
    //show26();
    //show27();
    //show28();
    //show29();
    //show30();
    //show31();
    //show32();
    //show33();
    //show34();
    //show35();
    //show36();
    //show37();
    //show38();
    //show39();
    //show40();
    //show41();
    //show42();
    //show43();
    //show44();
    //show45();
    //show46();
    show47();

    //yaku1();
}
